name = "my-blog-worker"
main = "src/index.ts"
compatibility_date = "2024-02-26"

[vars]
FRONTEND_URL = "https://choidaruhan.github.io"
ALLOW_LOCAL_AUTH = "true"

[[d1_databases]]
binding = "DB"
database_name = "my-blog-db"
database_id = "0498fc79-d432-4e59-8b16-e42eacd48371"
